#!/usr/bin/env python3
"""Tests for tools/generated_paths.py -- the single generated-file registry.

The registry exists so that unattended automation (the merge queue's
`worktree_is_safe` / `restore_generated_paths` / `regenerate_on_batch`) can
discard and rebuild files this repository GENERATES, and nothing else.

These tests pin the membership of that registry against the real gates, and
prove the specific wedge this file was extended to prevent: `tools/INDEX.md`
is generated by `tools/gen_tool_index.py` and guarded by a byte-identity
check, but was not registered -- so a batch whose union drifted it could not
be repaired by the queue and the queue could not publish the batch.

They also pin the interaction the registration must NOT break: registering a
generated artifact must not turn a genuine hand-edit into a silent auto-fix.
"""

import importlib.util
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "tools"
GEN_TOOL_INDEX = TOOLS / "gen_tool_index.py"


def _load(name, path):
    """Import a tools/ module by path without polluting sys.path."""
    spec = importlib.util.spec_from_file_location(name, str(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


generated_paths = _load("generated_paths_under_test", TOOLS / "generated_paths.py")


def _run(argv, cwd):
    """Run a python tool with an explicit cwd and utf-8 decoding."""
    return subprocess.run(
        [sys.executable] + [str(a) for a in argv],
        cwd=str(cwd), capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=120)


def _git(args, cwd):
    """git with identity forced per-invocation: never touches global config."""
    return subprocess.run(
        ["git", "-c", "user.email=t@example.invalid", "-c", "user.name=t"] + args,
        cwd=str(cwd), capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=120)


class ToolsRepoFixture(unittest.TestCase):
    """A throwaway git repo containing a real copy of gen_tool_index.py.

    Hermetic: a temp dir, its own git repo, per-invocation git identity, and
    the process cwd is never changed.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="aesop-genpaths-")
        self.root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        (self.root / "tools").mkdir()
        # The generator under test is the real one, not a stand-in.
        (self.root / "tools" / "gen_tool_index.py").write_text(
            GEN_TOOL_INDEX.read_text(encoding="utf-8"),
            encoding="utf-8", newline="\n")
        self.assertEqual(_git(["init", "-q"], self.root).returncode, 0)
        self.add_tool("alpha.py", "alpha purpose")
        self.regenerate()

    def add_tool(self, name, index_line):
        """Add a tracked tools/<name> carrying (or omitting) an INDEX: line."""
        body = ['#!/usr/bin/env python3', '"""Doc.']
        if index_line is not None:
            body.append("INDEX: %s" % index_line)
        body += ['"""', ""]
        (self.root / "tools" / name).write_text(
            "\n".join(body), encoding="utf-8", newline="\n")
        self.assertEqual(
            _git(["add", "--", "tools/%s" % name], self.root).returncode, 0)

    def check(self):
        """The byte-identity gate. 0 = in sync, 1 = drift or missing INDEX:."""
        return _run([GEN_TOOL_INDEX, "--root", self.root, "--check"], self.root)

    def regenerate(self):
        return _run(
            [GEN_TOOL_INDEX, "--root", self.root, "--regenerate"], self.root)

    def index_bytes(self):
        p = self.root / "tools" / "INDEX.md"
        return p.read_bytes() if p.exists() else None


class TestPredictedIndexWedge(ToolsRepoFixture):
    """The jam: a batch union drifts INDEX.md and nothing can repair it.

    Every member of an integration batch can be individually green while their
    union is not: each member adds a tool with its own INDEX: line, so each
    branch's INDEX.md is byte-identical to its own sources, and the merged tree
    is missing the other member's entry. The byte-identity gate then fails
    closed on a branch the queue already built -- the exact shape of the
    suite-count jam this registry was created for.
    """

    def test_union_of_two_green_members_drifts_the_index_gate(self):
        """Repro: each member alone is green; the union fails the gate."""
        self.assertEqual(self.check().returncode, 0, "baseline must be in sync")
        # Member A and member B each land a tool. Neither regenerates on top of
        # the other -- the merge does, and no member ever tested that tree.
        self.add_tool("beta.py", "beta purpose")
        self.add_tool("gamma.py", "gamma purpose")
        proc = self.check()
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)
        self.assertIn("out of date", proc.stderr)

    def test_index_md_is_a_registered_generated_path(self):
        """Without registration the queue can neither restore nor commit it."""
        self.assertIn("tools/INDEX.md", generated_paths.GENERATED_PATHS)
        self.assertTrue(generated_paths.is_generated("tools/INDEX.md"))
        # Windows porcelain output arrives with backslashes.
        self.assertTrue(generated_paths.is_generated("tools\\INDEX.md"))

    def test_unregistered_drift_would_be_rejected_as_overreach(self):
        """The precise mechanism of the wedge, asserted against real code.

        `regenerate_on_batch` commits a dirty path only when it is in the
        registry; anything else is `regenerator_overreach` and NOTHING is
        committed -- so before registration, an INDEX.md drift on the batch
        branch could not be repaired even if a generator had written it.
        """
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        dirty = ["tools/INDEX.md"]
        unregistered = [p for p in dirty if p not in merge_queue.GENERATED_PATHS]
        self.assertEqual(
            unregistered, [],
            "tools/INDEX.md is dirty-but-unregistered: regenerate_on_batch "
            "would row regenerator_overreach and commit nothing, and "
            "worktree_is_safe would refuse the whole pass")

    def test_a_registered_regenerator_repairs_the_drifted_union(self):
        """After registration the queue has a generator that closes the gate."""
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        argvs = [tuple(a) for a in merge_queue.REGENERATORS]
        self.assertIn(("tools/gen_tool_index.py", "--regenerate"), argvs)
        # And that generator really does repair the drifted union.
        self.add_tool("beta.py", "beta purpose")
        self.assertEqual(self.check().returncode, 1)
        self.assertEqual(self.regenerate().returncode, 0)
        self.assertEqual(self.check().returncode, 0)

    def test_every_registered_regenerator_accepts_its_flags(self):
        """A registry naming a flag the script rejects fails on every batch."""
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        for argv in merge_queue.REGENERATORS:
            script = REPO_ROOT / argv[0]
            self.assertTrue(script.exists(), "missing generator: %s" % argv[0])
            proc = _run([script, "--help"], REPO_ROOT)
            self.assertEqual(proc.returncode, 0, proc.stderr[:300])
            for flag in argv[1:]:
                self.assertIn(flag, proc.stdout,
                              "%s does not accept %s" % (argv[0], flag))


class TestRegistrationDoesNotWeakenTheByteIdentityGate(ToolsRepoFixture):
    """Registration must not make tampering silently auto-fixed.

    The worry is real and worth stating: adding a byte-identity-gated file to
    a registry that unattended automation may `git restore` and regenerate
    could, in principle, launder a hand-edit into green.

    It does not, because the registry's membership criterion is that the file
    is DERIVED. `tools/INDEX.md` is a pure function of the `INDEX:` lines in
    the tools/ sources, so the only edit registration can discard is an edit to
    the derived artifact itself -- which carries no information by
    construction. Every edit that means something lives in a source file, is
    NOT registered, and still faces the unchanged gate.
    """

    def test_regeneration_is_a_pure_function_of_the_sources(self):
        """A hand-edit to INDEX.md alone is information-free: regenerating
        reproduces the same bytes from unchanged sources."""
        before = self.index_bytes()
        p = self.root / "tools" / "INDEX.md"
        p.write_text(
            p.read_text(encoding="utf-8") + "\n- `ghost.py` -- invented\n",
            encoding="utf-8", newline="\n")
        self.assertEqual(self.check().returncode, 1, "the gate still sees it")
        self.assertEqual(self.regenerate().returncode, 0)
        self.assertEqual(self.index_bytes(), before)

    def test_a_tool_with_no_index_line_still_fails_closed(self):
        """The tamper that matters: registration cannot launder an
        undocumented tool into a green index. --regenerate refuses to write."""
        before = self.index_bytes()
        self.add_tool("sneaky.py", None)
        proc = self.regenerate()
        self.assertEqual(proc.returncode, 1, proc.stdout)
        self.assertIn("fail-closed", proc.stderr)
        self.assertEqual(self.index_bytes(), before,
                         "a failing generator must leave the tree untouched")
        self.assertEqual(self.check().returncode, 1)

    def test_editing_a_source_index_line_propagates_it_visibly(self):
        """Ground truth is the source, never the artifact: a tampered INDEX:
        line surfaces IN the regenerated index, in the diff, under review --
        it is not swallowed."""
        self.add_tool("alpha.py", "TAMPERED purpose")
        self.assertEqual(self.check().returncode, 1)
        self.assertEqual(self.regenerate().returncode, 0)
        body = (self.root / "tools" / "INDEX.md").read_text(encoding="utf-8")
        self.assertIn("TAMPERED purpose", body)

    def test_the_gate_itself_is_unchanged_by_registration(self):
        """Registration adds a repair path on the batch branch; it removes no
        check. The pushed branch and CI still run the same byte-identity gate,
        which still fails closed on drift."""
        self.add_tool("beta.py", "beta purpose")
        proc = self.check()
        self.assertEqual(proc.returncode, 1)
        self.assertIn("gen_tool_index.py --regenerate", proc.stderr)


class TestRegistryContract(unittest.TestCase):
    """Regression cover for the paths that were already registered."""

    def test_previously_registered_paths_survive(self):
        for path in ("tests/CLAUDE.md", "tools/CLAUDE.md"):
            self.assertIn(path, generated_paths.GENERATED_PATHS)
            self.assertTrue(generated_paths.is_generated(path))

    def test_registry_is_an_immutable_ascii_posix_tuple(self):
        registry = generated_paths.generated_paths()
        self.assertIsInstance(registry, tuple)
        self.assertEqual(registry, generated_paths.GENERATED_PATHS)
        for path in registry:
            self.assertEqual(path, path.encode("ascii").decode("ascii"))
            self.assertNotIn("\\", path)
            self.assertFalse(os.path.isabs(path))

    def test_registry_has_no_duplicates_and_is_sorted(self):
        registry = generated_paths.generated_paths()
        self.assertEqual(len(set(registry)), len(registry))
        self.assertEqual(list(registry), sorted(registry))

    def test_non_members_and_junk_are_not_generated(self):
        for path in ("tools/merge_queue.py", "README.md", "", None,
                     "tools/INDEX.md.bak", "docs/INDEX.md"):
            self.assertFalse(generated_paths.is_generated(path), path)

    def test_every_registered_path_is_tracked_in_this_repo(self):
        """Criterion 3: an untracked file is never restorable, never generated."""
        proc = _git(["ls-files", "--"] + list(generated_paths.GENERATED_PATHS),
                    REPO_ROOT)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        tracked = set(proc.stdout.split())
        self.assertEqual(set(generated_paths.GENERATED_PATHS) - tracked, set())

    def test_merge_queue_shares_the_registry_and_does_not_relist(self):
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        self.assertEqual(tuple(merge_queue.GENERATED_PATHS),
                         tuple(generated_paths.GENERATED_PATHS))


if __name__ == "__main__":
    unittest.main()
