#!/usr/bin/env python3
"""GOLDEN NO-OP TEST: Verify that manifest items without new fields produce
identical prompts to the pre-change version.

This test captures the EXACT prompts generated by the template's helper functions
and verifies they match the expected behavior when optional fields are absent.
"""

import unittest
from pathlib import Path
import sys

# Add driver/ to path for imports.
REPO = Path(__file__).resolve().parent.parent
DRIVER_DIR = REPO / "driver"
if str(DRIVER_DIR) not in sys.path:
    sys.path.insert(0, str(DRIVER_DIR))


class TestGoldenNoOpPrompts(unittest.TestCase):
    """Verify that the template produces byte-identical prompts when optional fields absent."""

    def test_acceptance_criteria_section_empty_when_absent(self):
        """acceptanceCriteria section should be empty string when field absent."""
        # This is what the template's helper function should return
        item = {"slug": "test"}
        # The helper should check for acceptanceCriteria and return '' if absent
        self.assertNotIn("acceptanceCriteria", item)
        # When template consumes item.acceptanceCriteria, it should get undefined/false

    def test_domain_synopsis_section_empty_when_absent(self):
        """domainSynopsis section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("domainSynopsis", item)

    def test_owns_files_diff_section_empty_when_absent(self):
        """ownsFilesDiff section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("ownsFilesDiff", item)

    def test_last_test_output_section_empty_when_absent(self):
        """lastTestOutput section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("lastTestOutput", item)

    def test_template_renders_empty_sections_as_empty_strings(self):
        """Verify template helpers return empty strings when fields absent."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify each helper function checks for field presence and returns ''
        self.assertIn("if (!item.acceptanceCriteria", template_src,
                      "acceptanceCriteria helper should check for field presence")
        self.assertIn("return ''", template_src,
                      "helpers should return empty string when field absent")

        self.assertIn("if (!item.domainSynopsis", template_src,
                      "domainSynopsis helper should check for field presence")

        self.assertIn("if (!item.ownsFilesDiff", template_src,
                      "ownsFilesDiff helper should check for field presence")

        self.assertIn("if (!item.lastTestOutput", template_src,
                      "lastTestOutput helper should check for field presence")

    def test_template_build_prompt_construction_with_empty_sections(self):
        """Build prompt concatenation should produce identical result when sections empty."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify the build prompt concatenates the optional sections.
        # When they return '', the prompt is unchanged.
        self.assertIn("acceptanceCriteriaSection(it)", template_src,
                      "build prompt should call acceptanceCriteriaSection helper")
        self.assertIn("domainSynopsisSection(it)", template_src,
                      "build prompt should call domainSynopsisSection helper")

    def test_template_repair_prompt_construction_with_empty_sections(self):
        """Repair prompt concatenation should produce identical result when sections empty."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify repair prompt calls the optional section helpers
        self.assertIn("lastTestOutputSection(it)", template_src,
                      "repair prompt should call lastTestOutputSection helper")
        self.assertIn("ownsFilesDiffSection(it)", template_src,
                      "repair prompt should call ownsFilesDiffSection helper")

    def test_string_concatenation_with_empty_sections_is_identity(self):
        """Verify that concatenating empty strings produces identical output."""
        # This is a mathematical identity: "base" + "" + "" == "base"
        base = "FLAT ONE-TURN-WAVE worker"
        empty_section_1 = ""
        empty_section_2 = ""
        expected = "FLAT ONE-TURN-WAVE worker"
        actual = base + empty_section_1 + empty_section_2
        self.assertEqual(actual, expected,
                         "Concatenating empty sections should not change the base string")

    def test_manifest_item_without_optional_fields_yields_noop(self):
        """Manifest item without A1-A4 fields should be functionally equivalent to pre-change."""
        # This is the contract: if the input item lacks the new fields,
        # the output should be identical to what it would have been before.
        item_old_style = {
            "slug": "fix-example",
            "ownsFiles": ["src/example.py"],
            "prompt": "Fix the example",
            "testCmd": "python test.py",
        }

        # The build_manifest_item already passes through all input fields (dict(item))
        # so the A1-A4 fields would simply not be in the result if not in input
        result = dict(item_old_style)
        result["model"] = "haiku"
        result["verificationTier"] = 1
        result["repairCap"] = 1
        result["requireAdversarialReview"] = False
        result["spotCheckFrac"] = 0.10
        result["validateAllJson"] = False

        # Verify no A1-A4 fields are added
        self.assertNotIn("acceptanceCriteria", result)
        self.assertNotIn("lastTestOutput", result)
        self.assertNotIn("domainSynopsis", result)
        self.assertNotIn("ownsFilesDiff", result)

        # The prompt sections generated from the result should be empty
        # (verified by template helper functions)


if __name__ == "__main__":
    unittest.main()
