#!/usr/bin/env python3
"""GOLDEN NO-OP TEST: Verify that manifest items without new fields produce
identical prompts to the pre-change version.

This test captures the EXACT prompts generated by the template's helper functions
and verifies they match the expected behavior when optional fields are absent.
"""

import unittest
from pathlib import Path
import sys

# Add driver/ to path for imports.
REPO = Path(__file__).resolve().parent.parent
DRIVER_DIR = REPO / "driver"
if str(DRIVER_DIR) not in sys.path:
    sys.path.insert(0, str(DRIVER_DIR))

from claude_code_driver import ClaudeCodeDriver  # noqa: E402
from wave_bridge import build_manifest_item  # noqa: E402


class TestGoldenNoOpPrompts(unittest.TestCase):
    """Verify that the template produces byte-identical prompts when optional fields absent."""

    def test_acceptance_criteria_section_empty_when_absent(self):
        """acceptanceCriteria section should be empty string when field absent."""
        # This is what the template's helper function should return
        item = {"slug": "test"}
        # The helper should check for acceptanceCriteria and return '' if absent
        self.assertNotIn("acceptanceCriteria", item)
        # When template consumes item.acceptanceCriteria, it should get undefined/false

    def test_domain_synopsis_section_empty_when_absent(self):
        """domainSynopsis section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("domainSynopsis", item)

    def test_owns_files_diff_section_empty_when_absent(self):
        """ownsFilesDiff section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("ownsFilesDiff", item)

    def test_last_test_output_section_empty_when_absent(self):
        """lastTestOutput section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("lastTestOutput", item)

    def test_initial_failed_test_output_section_empty_when_absent(self):
        """initialFailedTestOutput section should be empty string when field absent."""
        item = {"slug": "test"}
        self.assertNotIn("initialFailedTestOutput", item)

    def test_template_renders_empty_sections_as_empty_strings(self):
        """Verify template helpers return empty strings when fields absent."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify each helper function checks for field presence and returns ''
        self.assertIn("if (!item.acceptanceCriteria", template_src,
                      "acceptanceCriteria helper should check for field presence")
        self.assertIn("return ''", template_src,
                      "helpers should return empty string when field absent")

        self.assertIn("if (!item.domainSynopsis", template_src,
                      "domainSynopsis helper should check for field presence")

        self.assertIn("if (!item.ownsFilesDiff", template_src,
                      "ownsFilesDiff helper should check for field presence")

        self.assertIn("if (!item.lastTestOutput", template_src,
                      "lastTestOutput helper should check for field presence")

        self.assertIn("if (!item.initialFailedTestOutput", template_src,
                      "initialFailedTestOutput helper should check for field presence")

    def test_template_build_prompt_construction_with_empty_sections(self):
        """Build prompt concatenation should produce identical result when sections empty."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify the build prompt concatenates the optional sections.
        # When they return '', the prompt is unchanged.
        self.assertIn("acceptanceCriteriaSection(it)", template_src,
                      "build prompt should call acceptanceCriteriaSection helper")
        self.assertIn("domainSynopsisSection(it)", template_src,
                      "build prompt should call domainSynopsisSection helper")
        self.assertIn("initialFailedTestOutputSection(it)", template_src,
                      "build prompt should call initialFailedTestOutputSection helper")

    def test_template_repair_prompt_construction_with_empty_sections(self):
        """Repair prompt concatenation should produce identical result when sections empty."""
        template_path = REPO / "skills" / "buildsystem" / "wave-flat-dispatch.template.mjs"
        template_src = template_path.read_text()

        # Verify repair prompt calls the optional section helpers
        self.assertIn("lastTestOutputSection(it)", template_src,
                      "repair prompt should call lastTestOutputSection helper")
        self.assertIn("ownsFilesDiffSection(it)", template_src,
                      "repair prompt should call ownsFilesDiffSection helper")

    def test_string_concatenation_with_empty_sections_is_identity(self):
        """Verify that concatenating empty strings produces identical output."""
        # This is a mathematical identity: "base" + "" + "" == "base"
        base = "FLAT ONE-TURN-WAVE worker"
        empty_section_1 = ""
        empty_section_2 = ""
        expected = "FLAT ONE-TURN-WAVE worker"
        actual = base + empty_section_1 + empty_section_2
        self.assertEqual(actual, expected,
                         "Concatenating empty sections should not change the base string")

    def test_manifest_item_without_optional_fields_yields_noop(self):
        """Manifest item without ANY A1-A4 field AND no testCmd is the TRUE no-op:
        build_manifest_item's actual output carries none of the optional prompt
        sections, so the rendered build prompt stays byte-identical.
        """
        item_old_style = {
            "slug": "fix-example",
            "ownsFiles": ["src/example.py"],
            "prompt": "Fix the example",
            # Deliberately NO testCmd: this is what keeps this case a true no-op.
            # (Domain-specific baseline-derivation test below covers testCmd.)
        }

        # Call the REAL function, not a hand-simulated replica -- this is the
        # actual contract the template consumes.
        result = build_manifest_item(ClaudeCodeDriver(), item_old_style)

        self.assertEqual(result["model"], "haiku")
        self.assertEqual(result["verificationTier"], 1)
        self.assertEqual(result["repairCap"], 1)
        self.assertFalse(result["requireAdversarialReview"])
        self.assertEqual(result["spotCheckFrac"], 0.10)
        self.assertFalse(result["validateAllJson"])

        # Verify no A1-A4 fields are added: true no-op.
        self.assertNotIn("acceptanceCriteria", result)
        self.assertNotIn("lastTestOutput", result)
        self.assertNotIn("domainSynopsis", result)
        self.assertNotIn("ownsFilesDiff", result)

        # The prompt sections generated from the result should be empty
        # (verified by template helper functions)

    def test_manifest_item_with_testcmd_derives_baseline_acceptance_criteria(self):
        """DELIBERATE behavior change (not a regression): an item WITH a testCmd
        and no authored acceptanceCriteria now gets a derived baseline via
        build_manifest_item, so its build prompt WILL render an ACCEPTANCE
        CRITERIA section. This is context-engineering sharpening, gated by
        testCmd presence -- items without a testCmd remain untouched (see
        test_manifest_item_without_optional_fields_yields_noop, the true no-op).
        """
        item_with_testcmd = {
            "slug": "fix-example",
            "ownsFiles": ["src/example.py"],
            "prompt": "Fix the example",
            "testCmd": "python test.py",
        }

        result = build_manifest_item(ClaudeCodeDriver(), item_with_testcmd)

        self.assertEqual(
            result["acceptanceCriteria"],
            [
                {
                    "statement": "The item's tests pass with no regressions.",
                    "verifiable_by": "python test.py",
                }
            ],
        )
        # No other A1-A4 field is derived; only acceptanceCriteria.
        self.assertNotIn("lastTestOutput", result)
        self.assertNotIn("domainSynopsis", result)
        self.assertNotIn("ownsFilesDiff", result)


if __name__ == "__main__":
    unittest.main()
