#!/usr/bin/env python3

"""Generated-path registry (tools/generated_paths.py) + pre-push gate tests.

Three parts:
  1. The registry itself -- declaration shape, is_generated() matching rules,
     and the --list/--check CLI exit-code contract including the
     AESOP_ALLOW_GENERATED=1 designed-writer escape hatch.
  2. The pre-push wiring -- hooks/pre-push-policy.sh check_generated_paths() is
     sourced and driven directly against fixture git repos, proving it REJECTS a
     push whose diff touches a registered path, PASSES an ordinary push, and
     honors the escape hatch.
  3. The registration contract -- registry membership pinned against the real
     gates, plus the wedge this file was extended to prevent and the rule that
     registering an artifact must not turn a hand-edit into a silent auto-fix.

The registry exists so that unattended automation (the merge queue's
`worktree_is_safe` / `restore_generated_paths` / `regenerate_on_batch`) can
discard and rebuild files this repository GENERATES, and nothing else.

These tests pin the membership of that registry against the real gates, and
prove the specific wedge this file was extended to prevent: `tools/INDEX.md`
is generated by `tools/gen_tool_index.py` and guarded by a byte-identity
check, but was not registered -- so a batch whose union drifted it could not
be repaired by the queue and the queue could not publish the batch.

They also pin the interaction the registration must NOT break: registering a
generated artifact must not turn a genuine hand-edit into a silent auto-fix.
"""

import json
import os
import shutil


import importlib.util
import os

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL = REPO_ROOT / "tools" / "generated_paths.py"
HOOK = REPO_ROOT / "hooks" / "pre-push-policy.sh"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import tools.generated_paths as generated_paths  # noqa: E402

ZERO_SHA = "0" * 40


def _find_bash():
    """Locate a usable bash (Git Bash on Windows, never the WSL launcher).

    Mirrors tests/test_encoding_cp1252.py::_find_bash: plain "bash" on PATH can
    resolve to the WSL launcher in System32, which fails on runners with no
    WSL distribution installed.
    """
    if os.name != "nt":
        return shutil.which("bash")
    git_exe = shutil.which("git")
    if git_exe:
        git_root = Path(git_exe).parent.parent
        for candidate in (git_root / "bin" / "bash.exe",
                          git_root / "usr" / "bin" / "bash.exe"):
            if candidate.exists():
                return str(candidate)
    path_bash = shutil.which("bash")
    if path_bash and "system32" not in path_bash.lower():
        return path_bash
    return None


BASH = _find_bash()


class TestRegistryDeclaration(unittest.TestCase):

    def test_registry_is_non_empty_and_well_formed(self):
        self.assertGreater(len(generated_paths.REGISTRY), 0)
        for entry in generated_paths.REGISTRY:
            self.assertEqual(set(entry), {"pattern", "generator", "why"})
            for value in entry.values():
                self.assertIsInstance(value, str)
                self.assertTrue(value.strip())
            self.assertNotIn("\\", entry["pattern"], "patterns are POSIX-normalized")

    def test_seeded_paths_are_registered(self):
        for path in ("state/ledger/merge-telemetry.jsonl",
                     "tools/INDEX.md",
                     "tests/SUITE-COUNTS.md"):
            self.assertIsNotNone(generated_paths.is_generated(path), path)

    def test_every_entry_names_a_generator(self):
        for entry in generated_paths.REGISTRY:
            self.assertRegex(entry["generator"], r"\.(py|mjs|js|sh)")


class TestIsGenerated(unittest.TestCase):

    def test_authored_paths_are_not_registered(self):
        for path in ("tools/generated_paths.py", "README.md", "tests/CLAUDE.md",
                     "tools/CLAUDE.md", ".stateapi-baseline.json", "ui/serve.py"):
            self.assertIsNone(generated_paths.is_generated(path), path)

    def test_windows_separators_normalize(self):
        self.assertIsNotNone(generated_paths.is_generated("tools\\INDEX.md"))
        self.assertIsNotNone(generated_paths.is_generated(".\\tools\\INDEX.md"))

    def test_star_does_not_cross_a_directory_separator(self):
        # state/ledger/*.jsonl must NOT swallow a nested path.
        self.assertIsNotNone(generated_paths.is_generated("state/ledger/a.jsonl"))
        self.assertIsNone(generated_paths.is_generated("state/ledger/sub/a.jsonl"))
        self.assertIsNone(generated_paths.is_generated("state/a.jsonl"))

    def test_pattern_is_not_a_bare_suffix_match(self):
        # A same-named file elsewhere in the tree is authored, not generated.
        self.assertIsNone(generated_paths.is_generated("docs/INDEX.md"))
        self.assertIsNone(generated_paths.is_generated("bench/tools/INDEX.md"))

    def test_returned_entry_names_the_generator(self):
        entry = generated_paths.is_generated("tools/INDEX.md")
        self.assertIn("gen_tool_index.py", entry["generator"])


class CliTestCase(unittest.TestCase):

    def run_cli(self, args, stdin_text=None, env=None):
        run_env = dict(os.environ)
        run_env.pop(generated_paths.ALLOW_ENV, None)
        if env:
            run_env.update(env)
        return subprocess.run(  # subprocess-ok
            [sys.executable, str(TOOL)] + list(args),
            cwd=str(REPO_ROOT),
            input=stdin_text if stdin_text is not None else "",
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=60,
            env=run_env,
        )


class TestCliContract(CliTestCase):

    def test_list_exits_0_and_prints_every_pattern(self):
        res = self.run_cli(["--list"])
        self.assertEqual(res.returncode, 0, res.stderr)
        for entry in generated_paths.REGISTRY:
            self.assertIn(entry["pattern"], res.stdout)

    def test_list_json_is_parseable(self):
        res = self.run_cli(["--list", "--json"])
        self.assertEqual(res.returncode, 0, res.stderr)
        payload = json.loads(res.stdout)
        self.assertEqual(len(payload["registry"]), len(generated_paths.REGISTRY))

    def test_default_invocation_lists(self):
        self.assertEqual(self.run_cli([]).returncode, 0)

    def test_check_clean_paths_exits_0(self):
        res = self.run_cli(["--check", "tools/generated_paths.py", "README.md"])
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)

    def test_check_registered_path_exits_1(self):
        res = self.run_cli(["--check", "tools/INDEX.md"])
        self.assertEqual(res.returncode, 1)
        self.assertIn("tools/INDEX.md", res.stderr)

    def test_check_names_the_generator_in_the_message(self):
        res = self.run_cli(["--check", "tools/INDEX.md"])
        self.assertIn("gen_tool_index.py", res.stderr)

    def test_check_mixed_paths_exits_1(self):
        res = self.run_cli(["--check", "README.md", "tests/SUITE-COUNTS.md", "ui/serve.py"])
        self.assertEqual(res.returncode, 1)

    def test_check_no_paths_exits_0(self):
        self.assertEqual(self.run_cli(["--check"]).returncode, 0)

    def test_check_reads_paths_from_stdin(self):
        res = self.run_cli(["--check"], stdin_text="README.md\ntools/INDEX.md\n\n")
        self.assertEqual(res.returncode, 1)
        self.assertIn("tools/INDEX.md", res.stderr)

    def test_check_stdin_clean_exits_0(self):
        res = self.run_cli(["--check"], stdin_text="README.md\nui/serve.py\n")
        self.assertEqual(res.returncode, 0, res.stderr)

    def test_escape_hatch_downgrades_to_a_report(self):
        res = self.run_cli(["--check", "tools/INDEX.md"],
                           env={generated_paths.ALLOW_ENV: "1"})
        self.assertEqual(res.returncode, 0, res.stderr)
        self.assertIn("ALLOWED", res.stdout)
        self.assertIn("tools/INDEX.md", res.stdout)

    def test_escape_hatch_only_fires_on_exactly_1(self):
        for value in ("0", "true", "yes", ""):
            res = self.run_cli(["--check", "tools/INDEX.md"],
                               env={generated_paths.ALLOW_ENV: value})
            self.assertEqual(res.returncode, 1, "%s=%r must not open the gate"
                             % (generated_paths.ALLOW_ENV, value))

    def test_check_json_reports_hits(self):
        res = self.run_cli(["--check", "--json", "tools/INDEX.md"])
        self.assertEqual(res.returncode, 1)
        payload = json.loads(res.stdout)
        self.assertEqual(payload["count"], 1)
        self.assertFalse(payload["allowed"])

    def test_unknown_flag_exits_2(self):
        self.assertEqual(self.run_cli(["--check", "--disable"]).returncode, 2)

    def test_list_and_check_together_exit_2(self):
        self.assertEqual(self.run_cli(["--list", "--check"]).returncode, 2)

    def test_help_exits_0(self):
        res = self.run_cli(["--help"])
        self.assertEqual(res.returncode, 0)
        self.assertIn(generated_paths.ALLOW_ENV, res.stdout)


@unittest.skipIf(BASH is None, "usable bash unavailable")
class TestPrePushGate(unittest.TestCase):
    """Drive hooks/pre-push-policy.sh check_generated_paths() directly."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.driver = self.tmp / "drive.sh"
        self.driver.write_text(
            '#!/usr/bin/env bash\n'
            '. "%s"\n'
            'check_generated_paths\n'
            'exit $?\n' % HOOK.as_posix(),
            encoding="utf-8", newline="\n")

    def tearDown(self):
        self._tmp.cleanup()

    def git(self, repo, *args):
        return subprocess.run(  # subprocess-ok
            ["git"] + list(args), cwd=str(repo),
            capture_output=True, text=True, encoding="utf-8", timeout=120)

    def make_repo(self, changed_path, name="repo"):
        """Fixture repo: one base commit, then one commit touching changed_path."""
        repo = self.tmp / name
        (repo / Path(changed_path).parent).mkdir(parents=True, exist_ok=True)
        self.git(repo, "init", "-q", "-b", "main")
        self.git(repo, "config", "user.email", "test@example.com")
        self.git(repo, "config", "user.name", "Test User")
        (repo / "seed.txt").write_text("seed\n", encoding="utf-8", newline="\n")
        self.git(repo, "add", "-A")
        self.git(repo, "commit", "-q", "-m", "base")
        base = self.git(repo, "rev-parse", "HEAD").stdout.strip()
        (repo / changed_path).write_text("content\n", encoding="utf-8", newline="\n")
        self.git(repo, "add", "-A")
        self.git(repo, "commit", "-q", "-m", "change")
        head = self.git(repo, "rev-parse", "HEAD").stdout.strip()
        return repo, base, head

    def run_gate(self, repo, stdin_text, env=None):
        run_env = dict(os.environ)
        run_env.pop(generated_paths.ALLOW_ENV, None)
        # bash `test -f` chokes on Windows backslash paths, so hand the hook a
        # POSIX AESOP_ROOT -- the same shape `git rev-parse --show-toplevel`
        # produces when AESOP_ROOT is unset in a real push.
        run_env["AESOP_ROOT"] = REPO_ROOT.as_posix()
        if env:
            run_env.update(env)
        # Feed stdin from a BINARY file, never subprocess `input=` in text mode:
        # on Windows that translates every \n to \r\n, and the stray CR lands
        # inside the parsed remote-sha so `git diff <range>` silently matches
        # nothing. Real git pre-push always pipes LF.
        stdin_path = self.tmp / "prepush-stdin.txt"
        stdin_path.write_bytes(stdin_text.encode("utf-8"))
        with open(stdin_path, "rb") as handle:
            return subprocess.run(  # subprocess-ok
                [BASH, str(self.driver)], cwd=str(repo),
                stdin=handle, capture_output=True, text=True,
                encoding="utf-8", timeout=120, env=run_env)

    @staticmethod
    def tuple_for(base, head, branch="feature/lane"):
        return "refs/heads/%s %s refs/heads/%s %s\n" % (branch, head, branch, base)

    def test_rejects_push_touching_a_registered_generated_path(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen")
        res = self.run_gate(repo, self.tuple_for(base, head))
        self.assertEqual(res.returncode, 1, res.stdout + res.stderr)
        self.assertIn("tools/INDEX.md", res.stderr)

    def test_rejection_message_names_the_generator(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen2")
        res = self.run_gate(repo, self.tuple_for(base, head))
        self.assertIn("gen_tool_index.py", res.stderr)

    def test_passes_on_an_ordinary_path(self):
        repo, base, head = self.make_repo("tools/some_tool.py", "clean")
        res = self.run_gate(repo, self.tuple_for(base, head))
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)

    def test_passes_on_a_similarly_named_authored_path(self):
        repo, base, head = self.make_repo("docs/INDEX.md", "docsindex")
        res = self.run_gate(repo, self.tuple_for(base, head))
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)

    def test_escape_hatch_allows_the_regeneration_push(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen3")
        res = self.run_gate(repo, self.tuple_for(base, head),
                            env={generated_paths.ALLOW_ENV: "1"})
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)

    def test_empty_stdin_passes(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen4")
        self.assertEqual(self.run_gate(repo, "").returncode, 0)

    def test_delete_only_push_passes(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen5")
        tuple_text = "refs/heads/x %s refs/heads/x %s\n" % (ZERO_SHA, base)
        self.assertEqual(self.run_gate(repo, tuple_text).returncode, 0)

    def test_missing_tool_fails_open(self):
        repo, base, head = self.make_repo("tools/INDEX.md", "gen6")
        empty_root = self.tmp / "no-aesop"
        (empty_root / "state").mkdir(parents=True)
        res = self.run_gate(repo, self.tuple_for(base, head),
                            env={"AESOP_ROOT": empty_root.as_posix()})
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)

    def test_gate_is_wired_into_main(self):
        text = HOOK.read_text(encoding="utf-8")
        self.assertIn("check_generated_paths <<<", text)
        self.assertIn("generated_path_hand_edit", text)

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "tools"
GEN_TOOL_INDEX = TOOLS / "gen_tool_index.py"


def _load(name, path):
    """Import a tools/ module by path without polluting sys.path."""
    spec = importlib.util.spec_from_file_location(name, str(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


generated_paths = _load("generated_paths_under_test", TOOLS / "generated_paths.py")


def _run(argv, cwd):
    """Run a python tool with an explicit cwd and utf-8 decoding."""
    return subprocess.run(
        [sys.executable] + [str(a) for a in argv],
        cwd=str(cwd), capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=120)


def _git(args, cwd):
    """git with identity forced per-invocation: never touches global config."""
    return subprocess.run(
        ["git", "-c", "user.email=t@example.invalid", "-c", "user.name=t"] + args,
        cwd=str(cwd), capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=120)


class ToolsRepoFixture(unittest.TestCase):
    """A throwaway git repo containing a real copy of gen_tool_index.py.

    Hermetic: a temp dir, its own git repo, per-invocation git identity, and
    the process cwd is never changed.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="aesop-genpaths-")
        self.root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        (self.root / "tools").mkdir()
        # The generator under test is the real one, not a stand-in.
        (self.root / "tools" / "gen_tool_index.py").write_text(
            GEN_TOOL_INDEX.read_text(encoding="utf-8"),
            encoding="utf-8", newline="\n")
        self.assertEqual(_git(["init", "-q"], self.root).returncode, 0)
        self.add_tool("alpha.py", "alpha purpose")
        self.regenerate()

    def add_tool(self, name, index_line):
        """Add a tracked tools/<name> carrying (or omitting) an INDEX: line."""
        body = ['#!/usr/bin/env python3', '"""Doc.']
        if index_line is not None:
            body.append("INDEX: %s" % index_line)
        body += ['"""', ""]
        (self.root / "tools" / name).write_text(
            "\n".join(body), encoding="utf-8", newline="\n")
        self.assertEqual(
            _git(["add", "--", "tools/%s" % name], self.root).returncode, 0)

    def check(self):
        """The byte-identity gate. 0 = in sync, 1 = drift or missing INDEX:."""
        return _run([GEN_TOOL_INDEX, "--root", self.root, "--check"], self.root)

    def regenerate(self):
        return _run(
            [GEN_TOOL_INDEX, "--root", self.root, "--regenerate"], self.root)

    def index_bytes(self):
        p = self.root / "tools" / "INDEX.md"
        return p.read_bytes() if p.exists() else None


class TestPredictedIndexWedge(ToolsRepoFixture):
    """The jam: a batch union drifts INDEX.md and nothing can repair it.

    Every member of an integration batch can be individually green while their
    union is not: each member adds a tool with its own INDEX: line, so each
    branch's INDEX.md is byte-identical to its own sources, and the merged tree
    is missing the other member's entry. The byte-identity gate then fails
    closed on a branch the queue already built -- the exact shape of the
    suite-count jam this registry was created for.
    """

    def test_union_of_two_green_members_drifts_the_index_gate(self):
        """Repro: each member alone is green; the union fails the gate."""
        self.assertEqual(self.check().returncode, 0, "baseline must be in sync")
        # Member A and member B each land a tool. Neither regenerates on top of
        # the other -- the merge does, and no member ever tested that tree.
        self.add_tool("beta.py", "beta purpose")
        self.add_tool("gamma.py", "gamma purpose")
        proc = self.check()
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)
        self.assertIn("out of date", proc.stderr)

    def test_index_md_is_a_registered_generated_path(self):
        """Without registration the queue can neither restore nor commit it."""
        self.assertIn("tools/INDEX.md", generated_paths.GENERATED_PATHS)
        self.assertTrue(generated_paths.is_generated("tools/INDEX.md"))
        # Windows porcelain output arrives with backslashes.
        self.assertTrue(generated_paths.is_generated("tools\\INDEX.md"))

    def test_unregistered_drift_would_be_rejected_as_overreach(self):
        """The precise mechanism of the wedge, asserted against real code.

        `regenerate_on_batch` commits a dirty path only when it is in the
        registry; anything else is `regenerator_overreach` and NOTHING is
        committed -- so before registration, an INDEX.md drift on the batch
        branch could not be repaired even if a generator had written it.
        """
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        dirty = ["tools/INDEX.md"]
        unregistered = [p for p in dirty if p not in merge_queue.GENERATED_PATHS]
        self.assertEqual(
            unregistered, [],
            "tools/INDEX.md is dirty-but-unregistered: regenerate_on_batch "
            "would row regenerator_overreach and commit nothing, and "
            "worktree_is_safe would refuse the whole pass")

    def test_a_registered_regenerator_repairs_the_drifted_union(self):
        """After registration the queue has a generator that closes the gate."""
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        argvs = [tuple(a) for a in merge_queue.REGENERATORS]
        self.assertIn(("tools/gen_tool_index.py", "--regenerate"), argvs)
        # And that generator really does repair the drifted union.
        self.add_tool("beta.py", "beta purpose")
        self.assertEqual(self.check().returncode, 1)
        self.assertEqual(self.regenerate().returncode, 0)
        self.assertEqual(self.check().returncode, 0)

    def test_every_registered_regenerator_accepts_its_flags(self):
        """A registry naming a flag the script rejects fails on every batch."""
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        for argv in merge_queue.REGENERATORS:
            script = REPO_ROOT / argv[0]
            self.assertTrue(script.exists(), "missing generator: %s" % argv[0])
            proc = _run([script, "--help"], REPO_ROOT)
            self.assertEqual(proc.returncode, 0, proc.stderr[:300])
            for flag in argv[1:]:
                self.assertIn(flag, proc.stdout,
                              "%s does not accept %s" % (argv[0], flag))


class TestRegistrationDoesNotWeakenTheByteIdentityGate(ToolsRepoFixture):
    """Registration must not make tampering silently auto-fixed.

    The worry is real and worth stating: adding a byte-identity-gated file to
    a registry that unattended automation may `git restore` and regenerate
    could, in principle, launder a hand-edit into green.

    It does not, because the registry's membership criterion is that the file
    is DERIVED. `tools/INDEX.md` is a pure function of the `INDEX:` lines in
    the tools/ sources, so the only edit registration can discard is an edit to
    the derived artifact itself -- which carries no information by
    construction. Every edit that means something lives in a source file, is
    NOT registered, and still faces the unchanged gate.
    """

    def test_regeneration_is_a_pure_function_of_the_sources(self):
        """A hand-edit to INDEX.md alone is information-free: regenerating
        reproduces the same bytes from unchanged sources."""
        before = self.index_bytes()
        p = self.root / "tools" / "INDEX.md"
        p.write_text(
            p.read_text(encoding="utf-8") + "\n- `ghost.py` -- invented\n",
            encoding="utf-8", newline="\n")
        self.assertEqual(self.check().returncode, 1, "the gate still sees it")
        self.assertEqual(self.regenerate().returncode, 0)
        self.assertEqual(self.index_bytes(), before)

    def test_a_tool_with_no_index_line_still_fails_closed(self):
        """The tamper that matters: registration cannot launder an
        undocumented tool into a green index. --regenerate refuses to write."""
        before = self.index_bytes()
        self.add_tool("sneaky.py", None)
        proc = self.regenerate()
        self.assertEqual(proc.returncode, 1, proc.stdout)
        self.assertIn("fail-closed", proc.stderr)
        self.assertEqual(self.index_bytes(), before,
                         "a failing generator must leave the tree untouched")
        self.assertEqual(self.check().returncode, 1)

    def test_editing_a_source_index_line_propagates_it_visibly(self):
        """Ground truth is the source, never the artifact: a tampered INDEX:
        line surfaces IN the regenerated index, in the diff, under review --
        it is not swallowed."""
        self.add_tool("alpha.py", "TAMPERED purpose")
        self.assertEqual(self.check().returncode, 1)
        self.assertEqual(self.regenerate().returncode, 0)
        body = (self.root / "tools" / "INDEX.md").read_text(encoding="utf-8")
        self.assertIn("TAMPERED purpose", body)

    def test_the_gate_itself_is_unchanged_by_registration(self):
        """Registration adds a repair path on the batch branch; it removes no
        check. The pushed branch and CI still run the same byte-identity gate,
        which still fails closed on drift."""
        self.add_tool("beta.py", "beta purpose")
        proc = self.check()
        self.assertEqual(proc.returncode, 1)
        self.assertIn("gen_tool_index.py --regenerate", proc.stderr)


class TestRegistryContract(unittest.TestCase):
    """Regression cover for the paths that were already registered."""

    def test_previously_registered_paths_survive(self):
        for path in ("tests/CLAUDE.md", "tools/CLAUDE.md"):
            self.assertIn(path, generated_paths.GENERATED_PATHS)
            # is_restorable() is the predicate for the automation-restorable
            # tuple. is_generated() answers the narrower REGISTRY question
            # (every byte machine-written) that drives the push-blocking gate,
            # and these two prose-carrying docs are deliberately NOT in it.
            self.assertTrue(generated_paths.is_restorable(path))
            self.assertIsNone(generated_paths.is_generated(path))

    def test_index_md_is_in_both_registries(self):
        """tools/INDEX.md is fully generated AND needs union repair in a batch."""
        self.assertIn("tools/INDEX.md", generated_paths.GENERATED_PATHS)
        self.assertTrue(generated_paths.is_restorable("tools/INDEX.md"))
        self.assertIsNotNone(generated_paths.is_generated("tools/INDEX.md"))

    def test_registry_is_an_immutable_ascii_posix_tuple(self):
        registry = generated_paths.generated_paths()
        self.assertIsInstance(registry, tuple)
        self.assertEqual(registry, generated_paths.GENERATED_PATHS)
        for path in registry:
            self.assertEqual(path, path.encode("ascii").decode("ascii"))
            self.assertNotIn("\\", path)
            self.assertFalse(os.path.isabs(path))

    def test_registry_has_no_duplicates_and_is_sorted(self):
        registry = generated_paths.generated_paths()
        self.assertEqual(len(set(registry)), len(registry))
        self.assertEqual(list(registry), sorted(registry))

    def test_non_members_and_junk_are_not_generated(self):
        for path in ("tools/merge_queue.py", "README.md", "", None,
                     "tools/INDEX.md.bak", "docs/INDEX.md"):
            self.assertFalse(generated_paths.is_generated(path), path)

    def test_every_registered_path_is_tracked_in_this_repo(self):
        """Criterion 3: an untracked file is never restorable, never generated."""
        proc = _git(["ls-files", "--"] + list(generated_paths.GENERATED_PATHS),
                    REPO_ROOT)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        tracked = set(proc.stdout.split())
        self.assertEqual(set(generated_paths.GENERATED_PATHS) - tracked, set())

    def test_merge_queue_shares_the_registry_and_does_not_relist(self):
        merge_queue = _load("merge_queue_under_test", TOOLS / "merge_queue.py")
        self.assertEqual(tuple(merge_queue.GENERATED_PATHS),
                         tuple(generated_paths.GENERATED_PATHS))



if __name__ == "__main__":
    unittest.main()
