#!/usr/bin/env python3
"""Regenerating git merge driver for registered generated artifacts.
INDEX: Regenerating git merge driver for registered generated artifacts (`.gitattributes: tools/INDEX.md merge=aesop-regen`, registered per clone by `install_merge_drivers.py` as `python tools/generated_merge.py %O %A %B %L %P`); structured 3-way merge of index ENTRIES keyed by tool name (one-side add/delete/change wins, both-changed takes ours and reports it) rendered through `gen_tool_index.render`, so two lanes each adding a tool merge to an already-regenerated index instead of git `union`'s duplicated/unsorted lines (#784/#856/#739); when the working tree's sources do not yet agree with the merged entries (merge-ort runs drivers BEFORE it writes merged sources) it writes the per-worktree `.needs-regen` stamp (`git rev-parse --git-path aesop-needs-regen`) that `generated_push_gate.py` consumes at push; a registered path never conflicts (the artifact is a pure function of sources and the push gate repairs it); unregistered path exit 1 (git conflicts normally), usage exit 2

Why a driver and not just a gate: the gate (generated_push_gate.py) is the safety
net and would be sufficient for correctness, but it fires AFTER the lane has
already committed a stale merge and has to go back and fix it -- which is the
"lanes forget" loop. The driver makes the common case (two branches each add a
tool line) produce the regenerated bytes at merge time, so there is nothing to
forget.

Why the result is a structured 3-way merge rather than "run the generator":
git merge-ort (the default strategy since 2.34) computes the whole merge in
memory and only then writes the working tree, so a merge driver runs while the
tree still holds OURS. Regenerating from that tree would silently drop every
tool THEIRS added. The driver therefore merges the three index documents as
sets of (name -> one-liner) entries -- which is exactly what the generator
would produce from the union of both sides' sources, as long as each side had
regenerated its own index -- and renders them through the generator's own
`render()`, so the bytes are identical to a fresh regeneration. It then checks
the working tree: if `gen_tool_index.collect()` already agrees with the merged
entries the result IS a verified regeneration; if not, it writes the stamp so
the pre-push gate verifies the committed bytes against the tip's real sources.

Signature (git's five-placeholder form; %L is accepted and ignored):
    python tools/generated_merge.py %O %A %B %L %P
    python tools/generated_merge.py ANCESTOR OURS THEIRS [MARKER_SIZE] PATH [--root DIR]
The result is written to OURS (%A), as git requires.

Exit codes: 0 = merged and written (stamp may have been set); 1 = path not a
registered regenerable artifact, OURS untouched (git falls back to an ordinary
conflict); 2 = usage error.
"""

import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import gen_tool_index  # noqa: E402
import generated_paths  # noqa: E402

USAGE = (
    "usage: generated_merge.py ANCESTOR OURS THEIRS [MARKER_SIZE] PATH [--root DIR] [--quiet]\n"
    "       (git form: python tools/generated_merge.py %O %A %B %L %P)\n"
)

STAMP_NAME = "aesop-needs-regen"
ENTRY_RE = re.compile(r"^- `([^`]+)` -- (.*)$")
INDEX_PATH = "tools/INDEX.md"


def _read(path: Path) -> str:
    return path.read_bytes().decode("utf-8", errors="replace").replace("\r\n", "\n")


def parse_entries(text: str) -> Dict[str, str]:
    """Return the `- `name` -- desc` entries of an index document, in order."""
    out: Dict[str, str] = {}
    for line in text.splitlines():
        m = ENTRY_RE.match(line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def merge_entries(base: Dict[str, str], ours: Dict[str, str],
                  theirs: Dict[str, str]) -> Tuple[Dict[str, str], List[str]]:
    """Three-way merge keyed by entry name.

    Per name: identical on both sides -> keep; changed on exactly one side
    (added, deleted, or re-described) -> that side wins; changed differently on
    both -> ours wins and the name is reported. A deletion by one side stays
    deleted, unlike a line union.
    """
    merged: Dict[str, str] = {}
    conflicts: List[str] = []
    names: List[str] = []
    for source in (base, ours, theirs):
        for name in source:
            if name not in names:
                names.append(name)
    for name in names:
        o, a, b = base.get(name), ours.get(name), theirs.get(name)
        if a == b:
            result = a
        elif a == o:
            result = b
        elif b == o:
            result = a
        else:
            result = a
            conflicts.append(name)
        if result is not None:
            merged[name] = result
    return merged, conflicts


def render_index(entries) -> str:
    """Render (name, desc) pairs exactly as gen_tool_index would."""
    return gen_tool_index.render(list(entries))


def union_lines(ours: str, theirs: str) -> str:
    """Fallback for a registered artifact with no structured strategy: ours,
    then every line of theirs not already present, exact duplicates dropped."""
    seen = set()
    out: List[str] = []
    for line in ours.splitlines() + theirs.splitlines():
        if line in seen:
            continue
        seen.add(line)
        out.append(line)
    return "\n".join(out) + "\n"


def _git(root: Path, *args: str) -> Tuple[bool, str]:
    try:
        proc = subprocess.run(
            ["git"] + list(args), cwd=str(root), capture_output=True,
            text=True, encoding="utf-8", errors="replace", timeout=60)
    except (OSError, subprocess.SubprocessError):
        return False, ""
    return proc.returncode == 0, proc.stdout.strip()


def resolve_root(explicit: Optional[str]) -> Path:
    if explicit:
        return Path(explicit).resolve()
    ok, top = _git(Path.cwd(), "rev-parse", "--show-toplevel")
    return Path(top).resolve() if ok and top else Path.cwd().resolve()


def stamp_file(root: Path) -> Optional[Path]:
    """Per-worktree stamp location (inside the worktree's own git dir)."""
    ok, raw = _git(root, "rev-parse", "--git-path", STAMP_NAME)
    if not ok or not raw:
        return None
    path = Path(raw)
    return path if path.is_absolute() else root / path


def write_stamp(root: Path, rel_path: str) -> bool:
    stamp = stamp_file(root)
    if stamp is None:
        return False
    try:
        existing = stamp.read_text(encoding="utf-8").splitlines() if stamp.exists() else []
        if rel_path not in existing:
            existing.append(rel_path)
        stamp.parent.mkdir(parents=True, exist_ok=True)
        stamp.write_text("\n".join(existing) + "\n", encoding="utf-8", newline="\n")
    except OSError:
        return False
    return True


def tree_entries(root: Path) -> Optional[Dict[str, str]]:
    """What the generator would emit from the working tree right now, or None
    when it cannot (a tool without an INDEX: line, git unavailable, ...)."""
    try:
        entries, missing = gen_tool_index.collect(root)
    except Exception:  # noqa: BLE001 - any failure means "tree does not agree"
        return None
    if missing:
        return None
    return dict(entries)


def merge_index(root: Path, ancestor: str, ours: str, theirs: str, quiet: bool) -> Tuple[str, bool]:
    """Structured merge for tools/INDEX.md. Returns (result_text, needs_stamp)."""
    merged, conflicts = merge_entries(parse_entries(ancestor), parse_entries(ours),
                                      parse_entries(theirs))
    if conflicts and not quiet:
        sys.stderr.write("generated_merge: both sides re-described %s; took ours "
                         "(the push gate verifies against the sources)\n"
                         % ", ".join(conflicts))
    result = render_index(sorted(merged.items()))
    tree = tree_entries(root)
    needs_stamp = tree is None or tree != merged
    return result, needs_stamp


STRATEGIES = {
    INDEX_PATH: merge_index,
}


def main(argv: List[str]) -> int:
    if "--help" in argv or "-h" in argv:
        sys.stdout.write(__doc__ + "\n" + USAGE)
        return 0
    quiet = "--quiet" in argv
    root_arg: Optional[str] = None
    positional: List[str] = []
    it = iter(argv)
    for arg in it:
        if arg == "--quiet":
            continue
        if arg == "--root":
            root_arg = next(it, None)
            if root_arg is None:
                sys.stderr.write("generated_merge: --root needs a value\n" + USAGE)
                return 2
            continue
        if arg.startswith("-"):
            sys.stderr.write("generated_merge: unknown flag %r\n%s" % (arg, USAGE))
            return 2
        positional.append(arg)

    if len(positional) == 5:
        ancestor_p, ours_p, theirs_p, _marker, rel_path = positional
    elif len(positional) == 4:
        ancestor_p, ours_p, theirs_p, rel_path = positional
    else:
        sys.stderr.write("generated_merge: expected ANCESTOR OURS THEIRS [MARKER_SIZE] PATH "
                         "(register with %%O %%A %%B %%L %%P)\n%s" % USAGE)
        return 2

    rel_path = generated_paths.normalize(rel_path)
    if generated_paths.regenerator_for(rel_path) is None:
        sys.stderr.write("generated_merge: %s is not a registered regenerable artifact; "
                         "leaving the merge to git\n" % rel_path)
        return 1

    root = resolve_root(root_arg)
    ancestor_path, ours_path, theirs_path = (Path(ancestor_p), Path(ours_p), Path(theirs_p))
    try:
        ancestor = _read(ancestor_path) if ancestor_path.exists() else ""
        ours = _read(ours_path)
        theirs = _read(theirs_path)
    except OSError as exc:
        sys.stderr.write("generated_merge: cannot read merge sides: %s\n" % exc)
        return 2

    strategy = STRATEGIES.get(rel_path)
    if strategy is not None:
        result, needs_stamp = strategy(root, ancestor, ours, theirs, quiet)
    else:
        result, needs_stamp = union_lines(ours, theirs), True

    try:
        ours_path.write_bytes(result.encode("utf-8"))
    except OSError as exc:
        sys.stderr.write("generated_merge: cannot write result: %s\n" % exc)
        return 2

    if needs_stamp:
        if not write_stamp(root, rel_path) and not quiet:
            sys.stderr.write("generated_merge: could not write the %s stamp; the push gate "
                             "still verifies %s because it changed in the push range\n"
                             % (STAMP_NAME, rel_path))
        if not quiet:
            sys.stderr.write("generated_merge: merged %s; sources not yet on disk, "
                             "stamped for verification at push\n" % rel_path)
    elif not quiet:
        sys.stderr.write("generated_merge: merged %s (regenerated, tree agrees)\n" % rel_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
