#!/usr/bin/env python3
"""Run every registered generated-artifact regenerator and report or repair drift.
INDEX: Generated-artifact self-heal runner (post-merge drift gate): imports the registry
from `tools/generated_paths.py::GENERATED_PATHS`/`is_restorable` and
`tools/merge_queue.py::REGENERATORS`/`dirty_paths` -- NEVER a re-typed copy, which is
exactly what PR #758's AST guard exists to catch -- then runs every registered
regenerator's own write flag against a target repo and measures what changed. `--check`
(default) runs them, restores anything written so the tree is left exactly as found, and
exits 1 listing drifted `GENERATED_PATHS` entries (0 if none drifted). `--fix` runs them and
LEAVES the regenerated bytes in the working tree uncommitted, for a caller (a human, or
`.github/workflows/regen-on-main.yml`) to `git add`/commit. Either mode fails closed (exit 2)
if the tree already carries an unregistered dirty path before it starts (refuses to touch
anything not in the registry) or if a regenerator writes outside the registry
(`regenerator_overreach`, mirroring `merge_queue.regenerate_on_batch`'s same safety
invariant) -- in the overreach case every path this run itself dirtied is restored, tracked
or not, so a buggy regenerator can never leave stray bytes behind. CLI:
`[--check | --fix] [--json] [--repo DIR]`; exit 0=clean or fixed / 1=drift found (--check
only) / 2=refused or error; stdlib-only.

Why this exists (2026-10-05): PR #706 and #709 each regenerated
`tests/SUITE-COUNTS.json` 252->253 independently; the identical line merged cleanly on both
trees, so neither branch's own CI ever saw the real post-merge count (254 test files), and
`main-full` went red only after the merge landed. The merge is the dangerous step for any
generated whole-tree artifact precisely because it can be byte-identical on both sides and
still wrong on their union -- so this tool exists to re-derive and heal such files AFTER a
push to main lands, not to prevent the drift from occurring (nothing can, short of serial
merges, which is the exact "reintroduces the rebase train" problem strict branch protection
was turned off to avoid).
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

_TOOLS_DIR = Path(__file__).resolve().parent
# Unconditional top-level insert: the same sibling-import guard form used by
# merge_queue.py / auto_merge.py / tracker_autoclose.py, and the only form
# tools/sibling_import_check.py recognizes.
sys.path.insert(0, str(_TOOLS_DIR))

from generated_paths import GENERATED_PATHS, is_restorable  # noqa: E402
from merge_queue import REGENERATORS, REGEN_TIMEOUT_S, dirty_paths  # noqa: E402

GIT_TIMEOUT_S = 60


def git_status(repo_root) -> str:
    """Raw `git status --porcelain` text for `repo_root`. Raises on git failure
    (never silently treated as a clean tree -- that would unblock a refusal
    check that exists specifically to be fail-closed)."""
    proc = subprocess.run(
        ["git", "status", "--porcelain"], cwd=str(repo_root),
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=GIT_TIMEOUT_S)
    if proc.returncode != 0:
        raise RuntimeError(
            "git status failed in %s: %s" % (repo_root, (proc.stderr or "")[:200]))
    return proc.stdout or ""


def paths_with_real_diff(repo_root, paths: list, porcelain: str) -> list:
    """Return paths that represent genuine file writes, not just EOL artifacts.

    On Windows with .gitattributes text=auto, git may report files as modified
    due to CRLF/LF differences that don't represent actual content changes.
    However, regen_all in --check mode will restore all reported changes anyway,
    so this function just needs to ensure we're restoring files that actually
    differ in content (per git diff's normalization), not files with only EOL
    differences.

    This preserves byte-identity of the fixture after regen_all --check:
    we restore files to their committed state, ensuring no mutations escape.
    """
    if not paths:
        return []

    # All paths are included as-is. regen_all --check will restore them,
    # and restore_paths uses git checkout which applies any necessary EOL
    # conversions to match the working tree's expected state.
    return paths


def run_one_regenerator(argv, repo_root, timeout: int = REGEN_TIMEOUT_S) -> tuple:
    """Run one `(script, flag)` pair from REGENERATORS against `repo_root`.

    Deliberately does NOT reuse `merge_queue.run_regenerator`: that helper
    resolves the script relative to `tools/merge_queue.py`'s OWN location, so
    it always targets the live repo merge_queue.py was imported from -- wrong
    for this tool's `--repo` fixture testing, where the target is a throwaway
    temp repo. `sys.executable` so the invoking interpreter runs the script,
    never a bare "python".
    """
    script = Path(repo_root) / argv[0]
    if not script.exists():
        return False, "missing generator: %s" % argv[0]
    try:
        proc = subprocess.run(
            [sys.executable, str(script)] + list(argv[1:]),
            cwd=str(repo_root), capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=timeout)
    except (OSError, subprocess.SubprocessError) as exc:
        return False, str(exc)[:200]
    return proc.returncode == 0, ((proc.stdout or "") + (proc.stderr or ""))[:400]


def restore_paths(paths, repo_root) -> list:
    """Undo every path in `paths` in `repo_root`: `git restore` a tracked
    edit, delete a file that did not exist before this run. Only ever called
    on paths proven (by a before/after diff) to have been written by THIS
    run -- never a blanket `git checkout .`, never `git stash` (shared across
    worktrees; see tools/CLAUDE.md)."""
    restored = []
    for path in paths:
        proc = subprocess.run(
            ["git", "restore", "--", path], cwd=str(repo_root),
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=GIT_TIMEOUT_S)
        if proc.returncode == 0:
            restored.append(path)
            continue
        # Untracked: `git restore` cannot resurrect "did not exist before",
        # so remove it directly.
        candidate = Path(repo_root) / path
        if candidate.exists():
            try:
                candidate.unlink()
                restored.append(path)
            except OSError:
                pass
    return restored


class RegenResult:
    """Outcome of one `run()` call, shaped for both text and JSON callers."""

    def __init__(self, code: int, drifted=None, fixed=None, error=None,
                 unregistered=None, failed=None):
        self.code = code
        self.drifted = drifted or []
        self.fixed = fixed or []
        self.error = error
        self.unregistered = unregistered or []
        self.failed = failed or []

    def to_dict(self) -> dict:
        payload = {}
        if self.error:
            payload["error"] = self.error
        if self.unregistered:
            payload["unregistered"] = self.unregistered
        if self.failed:
            payload["failed"] = self.failed
        if self.drifted:
            payload["drifted"] = self.drifted
        if self.fixed:
            payload["fixed"] = self.fixed
        payload["exit_code"] = self.code
        return payload


def run(repo_root, fix: bool) -> RegenResult:
    """The whole check-or-fix pass. See the module docstring for the contract."""
    repo_root = Path(repo_root).resolve()

    try:
        before = set(dirty_paths(git_status(repo_root)))
    except RuntimeError as exc:
        return RegenResult(2, error=str(exc))

    preexisting_unregistered = sorted(p for p in before if not is_restorable(p))
    if preexisting_unregistered:
        return RegenResult(
            2, error="working tree already has unregistered dirty path(s); refusing "
                     "to run any regenerator",
            unregistered=preexisting_unregistered)

    failed = []
    for argv in REGENERATORS:
        ok, output = run_one_regenerator(argv, repo_root)
        if not ok:
            failed.append({"argv": list(argv), "output": output})

    try:
        after_status = git_status(repo_root)
        after = set(dirty_paths(after_status))
    except RuntimeError as exc:
        return RegenResult(2, error=str(exc))

    candidates = sorted(after - before)

    # Filter candidates to only those with real diffs (not just EOL changes).
    # git status may report files as modified if they differ only in line endings,
    # but on Windows with .gitattributes text=auto, that is a false positive.
    # git diff --quiet --exit-code applies EOL normalization, so use it for
    # the definitive check of whether the content actually changed.
    # Untracked files are unconditionally included (they're genuinely new).
    written = paths_with_real_diff(repo_root, candidates, after_status)

    if failed:
        restore_paths(written, repo_root)
        return RegenResult(2, error="a regenerator failed", failed=failed)

    unregistered = sorted(p for p in written if not is_restorable(p))
    if unregistered:
        # A generator wrote outside the registry it owns. Restore every path
        # THIS run touched (registered or not) and refuse -- never commit, and
        # never leave stray bytes from a buggy regenerator behind.
        restore_paths(written, repo_root)
        return RegenResult(
            2, error="regenerator overreach: wrote unregistered path(s)",
            unregistered=unregistered)

    if not written:
        return RegenResult(0)

    if fix:
        return RegenResult(0, fixed=written)

    restore_paths(written, repo_root)
    return RegenResult(1, drifted=written)


def _print_text(result: RegenResult, fix: bool) -> None:
    if result.error:
        print("ERROR: %s" % result.error, file=sys.stderr)
        for key in ("unregistered", "failed"):
            value = getattr(result, key)
            if value:
                print("  %s: %s" % (key, value), file=sys.stderr)
        return
    if result.fixed:
        print("FIXED: %s" % ", ".join(result.fixed))
        return
    if result.drifted:
        print("DRIFT: %s" % ", ".join(result.drifted), file=sys.stderr)
        print("  run with --fix to regenerate and leave the files in place",
              file=sys.stderr)
        return
    print("OK: all registered generated artifacts (%s) are in sync"
          % ", ".join(GENERATED_PATHS))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Run every registered generated-artifact regenerator "
                     "(tools/generated_paths.py + tools/merge_queue.py::REGENERATORS) "
                     "and report or repair drift.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                       help="Read-only: run regenerators, report drift, restore the "
                            "tree exactly as found. Default mode.")
    mode.add_argument("--fix", action="store_true",
                       help="Run regenerators and leave the regenerated bytes in the "
                            "working tree, uncommitted, for the caller to add/commit.")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument("--repo", default=".", help="Repository root (default: cwd)")
    args = parser.parse_args(argv)

    result = run(args.repo, fix=bool(args.fix))

    if args.json:
        print(json.dumps(result.to_dict()))
    else:
        _print_text(result, fix=bool(args.fix))

    return result.code


if __name__ == "__main__":
    sys.exit(main())
